title   vendiOS
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=arch archisolabel=%ARCHISO_LABEL% quiet loglevel=0 rd.systemd.show_status=false rd.udev.log_level=3 systemd.show_status=false vt.global_cursor_default=0
